spring:
  cloud:
    alicloud:
      access-key: YOUR_ACCESS_KEY
      secret-key: YOUR_SECRET_KEY
      oss:
        endpoint: YOUR_ENDPOINT
        bucket: YOUR_BUCKET
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
